name: "Spell and Grammar check"
description: "This action helps in cheking spellings and grammer using vale"
branding:
  color: green
  icon: shield

inputs:
  Parameters:
    description: "Custom parameters to vale CLI"
    required: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.Parameters }}
